services:
  tempo:
    build:
      dockerfile: Dockerfile.dev
      args:
        - REPO=${TEMPO_REPO}
        - COMMIT=${TEMPO_COMMIT}
        - RUST_VERSION=${RUST_VERSION}
        - TEMPO_BUILD_PROFILE=release
        - TEMPO_BUILD_TARGET_FOLDER=/app/target/release/tempo
